name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'microsoft'
        
    - name: Grant permission for gradlew
      run: chmod +x gradlew

    - name: DataGen
      run: ./gradlew runDatagen

    - name: Build
      run: ./gradlew build
        
    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: build/libs/
